### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by komplykated** [jpjacobpadilla/Google-Colab-Selenium#10]
I tried to get data for around 200 pages, it runs around 10 minutes then suddenly returned an error like this

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google_colab_selenium/undetected_chromedriver.py](https://localhost:8080/#) in __init__(self, options, keep_alive)
     39             with Spinner('Initializing Chromedriver', done='Initialized Chromedriver'):
---> 40                 super().__init__(
     41                     service=self.manager.service,

9 frames
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/root/.local/share/undetected_chromedriver/undetected_chromedriver'

The above exception was the direct cause of the following exception:

StartingChromeDriverError                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google_colab_selenium/undetected_chromedriver.py](https://localhost:8080/#) in __init__(self, options, keep_alive)
     45 
     46         except Exception as e:
---> 47             raise StartingChromeDriverError("""
     48                 Failed to start ChromeDriver. This could be due to a number
     49                 of factors, such as missing dependencies or incorrect

StartingChromeDriverError: 
                Failed to start ChromeDriver. This could be due to a number
                of factors, such as missing dependencies or incorrect
                configuration settings.
                
Does this allow for running multiple pages at the same time? Thanks a lot.

**Comment by jpjacobpadilla** [comment]
I've never seen that error before. Do you mind sending an example Notebook recreating the issue?

**Comment by komplykated** [comment]
> I've never seen that error before. Do you mind sending an example Notebook recreating the issue?

Yes Sir, here is the file

%pip install google-colab-selenium[undetected]
import google_colab_selenium as gs
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
import concurrent.futures
import datetime, time
import random
from tqdm import tqdm

categories = [
    {'cate_name': 'Mỹ Phẩm High-End',
     'url': 'https://hasaki.vn/danh-muc/my-pham-high-end-c1907.html'},
    {'cate_name': 'Chăm Sóc Da Mặt',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-da-mat-c4.html'},
    {'cate_name': 'Trang Điểm',
    'url': 'https://hasaki.vn/danh-muc/trang-diem-c23.html'},
    {'cate_name': 'Chăm Sóc Tóc',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-toc-c96.html'},
    {'cate_name': 'Chăm Sóc Cơ Thể',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-co-the-c12.html'},
    {'cate_name': 'Chăm Sóc Cá Nhân',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-ca-nhan-c2049.html'},
    {'cate_name': 'Thực Phẩm Chức Năng',
    'url': 'https://hasaki.vn/danh-muc/thuc-pham-chuc-nang-c156.html'}
]

def get_all(func_name, items):
    time.sleep(random.randrange(3, 10))
    output = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor, tqdm(total=len(items)) as pbar:
        futures = [executor.submit(func_name, item) for item in items]

        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result != None:
                output.append(result)
                pbar.update(1)

    return output


def flatten_list(nested_list):
    flattened_list = []
    for sublist in nested_list:
        flattened_list.extend(sublist)

    return flattened_list


def get_pages_for_each_category(category):
    cate_name = category['cate_name']
    url = category['url']

    # open source page
    driver = gs.UndetectedChrome()
    driver.get(url)
    time.sleep(2)

    # find total products of this category
    products = int(driver.find_element(By.CLASS_NAME, 'txt_999').text.replace('(','').replace('sản phẩm)', '').strip())

    # close browser
    driver.close()

    # find total pages of this category
    pages = None
    remainder = products % 40

    if remainder == 0:
        pages = products / 40
    else:
        pages = (products // 40) + 1

    # close browser
    driver.quit()

    return {
        'cate_name' : cate_name,
        'url': url,
        'total_pages': pages
        }

output = get_all(get_pages_for_each_category, categories)

output

**Comment by komplykated** [comment]
Yes Sir, here is the code

`%pip install google-colab-selenium[undetected]
import google_colab_selenium as gs
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
import concurrent.futures
import datetime, time
import random
from tqdm import tqdm

categories = [
    {'cate_name': 'Mỹ Phẩm High-End',
     'url': 'https://hasaki.vn/danh-muc/my-pham-high-end-c1907.html'},
    {'cate_name': 'Chăm Sóc Da Mặt',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-da-mat-c4.html'},
    {'cate_name': 'Trang Điểm',
    'url': 'https://hasaki.vn/danh-muc/trang-diem-c23.html'},
    {'cate_name': 'Chăm Sóc Tóc',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-toc-c96.html'},
    {'cate_name': 'Chăm Sóc Cơ Thể',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-co-the-c12.html'},
    {'cate_name': 'Chăm Sóc Cá Nhân',
    'url': 'https://hasaki.vn/danh-muc/cham-soc-ca-nhan-c2049.html'},
    {'cate_name': 'Thực Phẩm Chức Năng',
    'url': 'https://hasaki.vn/danh-muc/thuc-pham-chuc-nang-c156.html'}
]


def get_all(func_name, items):
    time.sleep(random.randrange(3, 10))
    output = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor, tqdm(total=len(items)) as pbar:
        futures = [executor.submit(func_name, item) for item in items]

        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result != None:
                output.append(result)
                pbar.update(1)

    return output


def flatten_list(nested_list):
    flattened_list = []
    for sublist in nested_list:
        flattened_list.extend(sublist)

    return flattened_list


def get_pages_for_each_category(category):
    cate_name = category['cate_name']
    url = category['url']

    # open source page
    driver = gs.UndetectedChrome()
    driver.get(url)
    time.sleep(2)

    # find total products of this category
    products = int(driver.find_element(By.CLASS_NAME, 'txt_999').text.replace('(','').replace('sản phẩm)', '').strip())

    # close browser
    driver.close()

    # find total pages of this category
    pages = None
    remainder = products % 40

    if remainder == 0:
        pages = products / 40
    else:
        pages = (products // 40) + 1

    # close browser
    driver.quit()

    return {
        'cate_name' : cate_name,
        'url': url,
        'total_pages': pages
        }

output = get_all(get_pages_for_each_category, categories)

output`

**Comment by komplykated** [comment]
Yes Sir, here is the file
[HA_202407_testing.zip](https://github.com/user-attachments/files/16229407/HA_202407_testing.zip)

**Comment by jpjacobpadilla** [comment]
Thanks for the example notebook. I'll try to fix it this weekend!

**Comment by komplykated** [comment]
> Thanks for the example notebook. I'll try to fix it this weekend!

thank bro

**Comment by jpjacobpadilla** [comment]
This issue is essentially just a race condition. I've released a new version of the package (1.0.14) which makes this Google-Colab-Selenium thread-safe!

**Comment by komplykated** [comment]
> This issue is essentially just a race condition. I've released a new version of the package (1.0.14) which makes this Google-Colab-Selenium thread-safe!

It works. Thanks a lot.
