### ISSUE TITLE
Google is able to detect the Undetectable version

### ISSUE THREAD

**Issue by abhishek-seo** [jpjacobpadilla/Google-Colab-Selenium#11]
Hi. I am trying to login to Gmail using this package but Google can detect the bot. 

Here is my code - 

```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from seleniumbase import Driver
import random
import pandas as pd
from IPython.core.display import display, HTML
import pygsheets
import google_colab_selenium as gs
from selenium.webdriver.chrome.options import Options

driver = gs.UndetectedChrome()
```

Then I have written a function to enter email and password which works with undetected chrome locally but does not work on Google colab and I can see this - 

![image](https://github.com/user-attachments/assets/493e176c-c99b-46b1-83d9-683c1b320b92)

Any solution? Thanks

**Comment by jpjacobpadilla** [comment]
Hi, This may have something to do with running Undetected-Chromedriver in headless vs non-headless mode or the IP address of the Google Colab Notebook. Does This program work on your computer when you set Undetected-Chromedriver to "headless"?
