### ISSUE TITLE
Failed to update and upgrade APT

### ISSUE THREAD

**Issue by capo11** [jpjacobpadilla/Google-Colab-Selenium#16]
Hey, unfortunately I got this error running the Chrome and UndetectedChrome driver, I used the same code in the previous days without any issues, so I don't know if something changed from yesterday.

![failed to update APT](https://github.com/user-attachments/assets/a3c6ce1a-f38e-4f44-9dd8-241c165c9dbe)

**Comment by jpjacobpadilla** [comment]
Hello, thanks for using my project! It looks like the example notebook in the README.md works correctly. Would you mind sending me a notebook recreating the issue that you're encountering?
