### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by jerrylin07** [jpjacobpadilla/Google-Colab-Selenium#2]
![image](https://github.com/jpjacobpadilla/Google-Colab-Selenium/assets/58316105/79676b7a-0970-49d7-bf61-e0fc15b37757)

**Comment by jpjacobpadilla** [comment]
Apologies! I found the issue and am fixing it now.

**Comment by jerrylin07** [comment]
Thank you for such a prompt reply, this module is the best selenium in google colab solution I've used so far!

**Comment by jpjacobpadilla** [comment]
Version 1.0.11 is now out. The main patch is that the package now automatically updates and upgrades the Advanced Package Tool, which is used to download Google Chrome.

Another version will come out soon to make this patch more elegant.
