### ISSUE TITLE
Failed to start Chromedriver

### ISSUE THREAD

**Issue by wanderingkoala** [jpjacobpadilla/Google-Colab-Selenium#3]
Hey Jacob, I was trying to run the Undetected Chrome driver on your sample colab file. Seems like it's running into a problem. 
I was hoping you could help fix the issue. Here's the error message I'm getting.

[/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/patcher.py](https://localhost:8080/#) in fetch_package(self)
    286         logger.debug("downloading from %s" % download_url)
--> 287         return urlretrieve(download_url)[0]
    288 

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in urlretrieve(url, filename, reporthook, data)
    240 
--> 241     with contextlib.closing(urlopen(url, data)) as fp:
    242         headers = fp.info()

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    215         opener = _opener
--> 216     return opener.open(url, data, timeout)
    217 

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in open(self, fullurl, data, timeout)
    524             meth = getattr(processor, meth_name)
--> 525             response = meth(req, response)
    526 

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_response(self, request, response)
    633         if not (200 <= code < 300):
--> 634             response = self.parent.error(
    635                 'http', request, response, code, msg, hdrs)

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in error(self, proto, *args)
    562             args = (dict, 'default', 'http_error_default') + orig_args
--> 563             return self._call_chain(*args)
    564 

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in _call_chain(self, chain, kind, meth_name, *args)
    495             func = getattr(handler, meth_name)
--> 496             result = func(*args)
    497             if result is not None:

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    642     def http_error_default(self, req, fp, code, msg, hdrs):
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 

**HTTPError: HTTP Error 404: Not Found**

The above exception was the direct cause of the following exception:

StartingChromeDriverError                 Traceback (most recent call last)
[<ipython-input-7-151b8ccdea17>](https://localhost:8080/#) in <cell line: 1>()
----> 1 driver = gs.UndetectedChrome()
      2 driver.get('https://www.google.com/')
      3 print(driver.title)
      4 driver.quit()

[/usr/local/lib/python3.10/dist-packages/google_colab_selenium/undetected_chromedriver.py](https://localhost:8080/#) in __init__(self, options, keep_alive)
     45 
     46         except Exception as e:
---> 47             raise StartingChromeDriverError("""
     48                 Failed to start ChromeDriver. This could be due to a number
     49                 of factors, such as missing dependencies or incorrect

StartingChromeDriverError: 
                Failed to start ChromeDriver. This could be due to a number
                of factors, such as missing dependencies or incorrect
                configuration settings.

**Comment by jpjacobpadilla** [comment]
It appears as though the regular version of Selenium works fine and it's just an issue with Undeteced-Chrome Driver. I'll take a look into it, but for now I'd recommend changing this line of code:

`driver = gs.UndetectedChrome()`

to:


`driver = gs.ChromeDriver()`

**Comment by jpjacobpadilla** [comment]
undetected-chromedriver problem resolved.
