### ISSUE TITLE
Google Search

### ISSUE THREAD

**Issue by iwo9** [jpjacobpadilla/Google-Colab-Selenium#4]
Hey, how would we use the search bar in google here? Trying 
search_box = driver.find_element_by_name("q")
but the find_element_by_name object doesn't seem to be here

**Comment by jpjacobpadilla** [comment]
I believe all of the `find_element_by_*` have been [deprecated](https://stackoverflow.com/questions/69875125/find-element-by-commands-are-deprecated-in-selenium) and are no longer in Python Selenium. Instead try using `find_element(By.NAME, 'name')`


Like this:

```python
from selenium.webdriver.common.by import By

driver = gs.ChromeDriver()
driver.get('https://google.com')
element = driver.find_element(By.NAME, "q")
print(element.tag_name)
driver.quit()
```

**Comment by iwo9** [comment]
Thanks!
