### ISSUE TITLE
issue regarding colab_selenium

### ISSUE THREAD

**Issue by Cwei13j** [jpjacobpadilla/Google-Colab-Selenium#5]
CalledProcessError: Command '['sudo', 'apt', 'upgrade']' returned non-zero exit status 100.

The above exception was the direct cause of the following exception:

GoogleColabSeleniumError                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/google_colab_selenium/colab_selenium_manager.py](https://localhost:8080/#) in update_upgrade_apt(cls)
     49 
     50         except Exception as e:
---> 51             raise GoogleColabSeleniumError('Failed to update and upgrade APT') from e
     52 
     53         else:

GoogleColabSeleniumError: Failed to update and upgrade APT
	
        If you believe this isn't due to a configuration error on your end, please
        report the issue with any details you can provide about the steps leading
        up to this error.

**Comment by jpjacobpadilla** [comment]
Can you send a Notebook recreating the error? The package seems to be working as expected on the example Notebook (in the README.md)
