### ISSUE TITLE
An error will occur

### ISSUE THREAD

**Issue by Munehira-Hiroshi** [jpjacobpadilla/Google-Colab-Selenium#6]
```
!pip install google-colab-selenium
import google_colab_selenium as gs
driver = gs.Chrome() # <----Error
```

**Comment by jpjacobpadilla** [comment]
Thanks for bringing this to my attention.

It looks like Selenium 4.20.0 was released today, which is causing the issue (since it still works on 4.19.0).

I'll see If I can find a fix.

**Comment by jpjacobpadilla** [comment]
Google-Colab-Selenium version 1.0.13 is out now, which adapts to the changes made in the new Selenium version.

**Comment by Munehira-Hiroshi** [comment]
Thank you!
